### ISSUE TITLE
Consul 0.6.3 docker image

### ISSUE THREAD

**Issue by StefanScherer** [hypriot/rpi-consul#1]
Reported by @alexellis  
https://github.com/hashicorp/consul/issues/74#issuecomment-172259871

> @highlyunavailable @StefanScherer Hi again Stefan, after finding this thread and spending ages trying to build on ARM docker.. the binary comes as welcome news. We really need some official ARM images for things like Consul.
> 
> Ref: #125 (says no consul binary available on arm)
> 
> I'm trying to set up a multi-host docker 1.9.1 ARM cluster with swarm, so the documentation calls for Consul. Anyway this is what I've put together:

```
FROM armhf/ubuntu
RUN apt-get update && apt-get -qy install \
 wget unzip
WORKDIR /root/
RUN wget \
 https://releases.hashicorp.com/consul/0.6.3/consul_0.6.3_linux_arm.zip
RUN mkdir /data
RUN mkdir /ui
RUN unzip consul*.zip -d /usr/local/bin/

RUN consul version

EXPOSE 8300 8301 8301/udp 8302 8302/udp 8400 8500 53/udp

VOLUME ["/data"]
ADD ./config /config/

ENV DNS_RESOLVES consul
ENV DNS_PORT 8600

ENTRYPOINT ["/usr/local/bin/consul", "agent", "-config-dir=/config"]
```

> agent.config

```
{
    "client_addr": "0.0.0.0",
    "bootstrap": true,
    "server": true,
    "data_dir": "/data",
    "leave_on_terminate": true,
    "dns_config": {
        "allow_stale": true,
        "max_stale": "1s"
    }
}
```

**Comment by firecyberice** [comment]
@StefanScherer,  @alexellis have a look at https://github.com/hypriot/rpi-consul/commit/099aac8fc5a86b9c29999ba099d92861812140ec

https://github.com/hypriot/rpi-consul/pull/2

**Comment by StefanScherer** [comment]
@firecyberice That's cool!

**Comment by Govinda-Fichtner** [comment]
Closing this with https://github.com/hypriot/rpi-consul/releases/tag/v0.6.3
